### ISSUE TITLE
Need rebuild

### ISSUE THREAD

**Issue by an3park** [YoshieraHuang/node-onvif-ts#2]
Latest bug still exist.
[fix counter for profiles](https://github.com/YoshieraHuang/node-onvif-ts/commit/f0f00e3a2e9c0371548ef28dd742ca59fa7b3cc3)
Please rebuild and reload to npm.

**Comment by YoshieraHuang** [comment]
OK, I rebuild the repostiry and the latest version at npm is 0.1.7. Could you check where the bug still exist or not?

**Comment by an3park** [comment]
It works good.
